[tools]
bat = "latest"
bat-extras = "latest"
deno = "latest"
dotnet = "latest"
erlang = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gleam = "latest"
glow = "latest"
go = "latest"
helix = "latest"
just = "latest"
lazygit = "latest"
luajit = "latest"
neovim = "latest"
node = "22"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
